#NOTE: INCLUDE / AT END OF EACH PATH!
paths:
  raw_reads: /c3se/NOBACKUP/groups/c3-c3se605-19-3/data/fastqfiles/
  filtered_reads: /c3se/NOBACKUP/groups/c3-c3se605-19-3/data/filtered_reads/
  motusfiles: /c3se/NOBACKUP/groups/c3-c3se605-19-3/data/motusfiles/
  chocophlan: /c3se/NOBACKUP/groups/c3-c3se605-19-3/data/chocophlanDB/chocophlan/
  uniref: /c3se/NOBACKUP/groups/c3-c3se605-19-3/data/UniRef90/uniref/
  reads_humann2: /c3se/NOBACKUP/groups/c3-c3se605-19-3/data/reads_humann2/
  output_humann2: /c3se/NOBACKUP/groups/c3-c3se605-19-3/data/output_humann2/
envs:
  humann2: /c3se/NOBACKUP/users/angelol/envs/humann2.yml
